/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicCodeEditor: typeof import('./src/components/Editor/src/BasicCodeEditor.vue')['default']
    BasicHelp: typeof import('./src/components/Basic/src/BasicHelp.vue')['default']
    DraggableTransitionGroup: typeof import('./src/components/Drag/src/DraggableTransitionGroup.vue')['default']
    DragSlot: typeof import('./src/components/Drag/src/DragSlot.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabPanel: typeof import('element-plus/es')['ElTabPanel']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    JsonEditor: typeof import('./src/components/Editor/src/JsonEditor.vue')['default']
    JsonEditro: typeof import('./src/components/Editor/src/JsonEditro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
